<?php
// Auto generated by helhum/typo3-config-handling
// Do not edit this file
$configLoader = \Helhum\Typo3ConfigHandling\ConfigLoaderFactory::buildLoader(
    \TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()->isProduction() ? 'prod' : 'dev'
);
$GLOBALS['TYPO3_CONF_VARS'] = array_replace_recursive(
    $GLOBALS['TYPO3_CONF_VARS'],
    $configLoader->load()
);
