EXTENSIONS:
    backend:
        backendFavicon: ''
        backendLogo: ''
        loginBackgroundImage: ''
        loginFootnote: ''
        loginHighlightColor: ''
        loginLogo: ''
    extensionmanager:
        automaticInstallation: '1'
        offlineMode: '0'
    scheduler:
        maxLifetime: '1440'
        showSampleTasks: '1'
