EXTCONF:
    sentry:
        # Set dsn to the dsn found in your Sentry project settings to activate Sentry logging
        dsn: null
        # Any string to name your environment
        environment: null
        # Array of class names that implement \Helhum\SentryTypo3\Integration\ContextInterface
        typo3_integrations: null
        # default when nothing is set:
#        typo3_integrations:
#            -  Helhum\SentryTypo3\Integration\Typo3Context
#            -  Helhum\SentryTypo3\Integration\RequestContext
#            -  Helhum\SentryTypo3\Integration\CommandContext
#            -  Helhum\SentryTypo3\Integration\UserContext
