<?php
declare(strict_types=1);
namespace Helhum\Typo3ConfigHandling\Command;

/***************************************************************
 *  Copyright notice
 *
 *  (c) 2017 Helmut Hummel <info@helhum.io>
 *  All rights reserved
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  A copy is found in the text file GPL.txt and important notices to the license
 *  from the author is found in LICENSE.txt distributed with these scripts.
 *
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

use Helhum\Typo3Console\Mvc\Cli\CommandDispatcher;
use Helhum\Typo3Console\Mvc\Controller\CommandController;
use TYPO3\CMS\Core\Utility\ArrayUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class SettingsCommandController extends CommandController
{
    /**
     * @var string
     */
    private $localConfigurationFile;

    public function __construct()
    {
        $this->localConfigurationFile = getenv('TYPO3_PATH_ROOT') . '/typo3conf/LocalConfiguration.php';
    }

    /**
     * Dump a static LocalConfiguration.php file
     *
     * The values are complied to respect all settings managed by the configuration loader.
     *
     * @param bool $noDev When set, only LocalConfiguration.php is written to contain the merged configuration ready for production
     */
    public function dumpCommand($noDev = false)
    {
        if (file_exists($this->localConfigurationFile) && !$this->isAutoGenerated()) {
            CommandDispatcher::createFromCommandRun()->executeCommand('settings:extract');
        }
        $localConfigurationFileContent = '<?php'
            . chr(10)
            . ' // Auto generated by helhum/typo3-config-handling'
            . chr(10)
            . ' // Do not edit this file'
            . chr(10);
        if ($noDev) {
            $localConfigurationFileContent .= 'return ' . chr(10);
            $configLoader = \Helhum\Typo3ConfigHandling\ConfigLoaderFactory::buildLoader(
                \TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()->isProduction() ? 'production' : 'development'
            );
            $localConfigurationFileContent .= ArrayUtility::arrayExport($configLoader->load());
            $localConfigurationFileContent .= ';' . chr(10);
        } else {
            copy(
                dirname(dirname(__DIR__)) . '/res/AdditionalConfiguration.php',
                getenv('TYPO3_PATH_ROOT') . '/typo3conf/AdditionalConfiguration.php'
            );
            $localConfigurationFileContent .= 'return [];';
        }
        file_put_contents(
            $this->localConfigurationFile,
            $localConfigurationFileContent
        );
    }

    public function extractCommand()
    {
        if (!file_exists($this->localConfigurationFile)) {
            $this->outputLine('<warning>LocalConfiguration.php does not exist. Nothing to extract</warning>');
            return;
        }
        if ($this->isAutoGenerated()) {
            $this->outputLine('<info>LocalConfiguration.php is already generated. Nothing to extract.</info>');
            return;
        }
        $settings = require $this->localConfigurationFile;
        try {
            $extensionsSettings = ArrayUtility::getValueByPath($settings, 'EXT/extConf');
            foreach ($extensionsSettings as $extensionKey => $extensionSettings) {
                $this->extractExtensionSettings($extensionKey, unserialize($extensionSettings, [false]));
            }
            $this->outputLine('<info>Extracted extension settings to conf/extension directory</info>');
        } catch (\RuntimeException $e) {
            $this->outputLine('<warning>No extension settings wer found</warning>');
        }
    }

    private function isAutoGenerated(): bool
    {
        if (!file_exists($this->localConfigurationFile)) {
            return false;
        }
        return false !== strpos(file_get_contents($this->localConfigurationFile), 'Auto generated by helhum/typo3-config-handling');
    }

    private function extractExtensionSettings(string $extensionKey, array $extensionSettings)
    {
        if (!is_dir($extensionSettingsDir = getenv('TYPO3_PATH_COMPOSER_ROOT') . '/conf/extension')) {
            GeneralUtility::mkdir_deep($extensionSettingsDir);
        }
        $extractedSettings = [];
        if (file_exists($extensionSettingsFile = $extensionSettingsDir . "/$extensionKey.php")) {
            $extractedSettings = require $extensionSettingsFile;
        }
        $extractedSettings = array_replace_recursive($extractedSettings, $extensionSettings);
        file_put_contents(
            $extensionSettingsFile,
            '<?php'
            . chr(10)
            . 'return '
            . ArrayUtility::arrayExport($extractedSettings)
            . ';'
            . chr(10)
        );
    }
}
