<?php
namespace Helhum\Typo3ConfigHandling\Command;

/***************************************************************
 *  Copyright notice
 *
 *  (c) 2017 Helmut Hummel <info@helhum.io>
 *  All rights reserved
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  A copy is found in the text file GPL.txt and important notices to the license
 *  from the author is found in LICENSE.txt distributed with these scripts.
 *
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

use Helhum\Typo3Console\Mvc\Controller\CommandController;
use TYPO3\CMS\Core\Utility\ArrayUtility;

class SettingsCommandController extends CommandController
{
    /**
     * Dump a static LocalConfiguration.php file
     *
     * The values are complied to respect all settings managed by the configuration loader.
     *
     * @param bool $dev When set, an AdditionalConfiguration.php is written as well to respect dynamic changes to configuration
     */
    public function dumpCommand($dev = false)
    {
        $localConfigurationFile = getenv('TYPO3_PATH_ROOT') . '/typo3conf/LocalConfiguration.php';
        $localConfigurationFileContent = '<?php'
            . chr(10)
            . ' // Auto generated by helhum/typo3-config-handling'
            . chr(10)
            . ' // Do not edit this file'
            . chr(10);
        if ($dev) {
            copy(
                dirname(dirname(__DIR__)) . '/res/AdditionalConfiguration.php',
                getenv('TYPO3_PATH_ROOT') . '/typo3conf/AdditionalConfiguration.php'
            );
            $localConfigurationFileContent .= 'return [];';
        } else {
            $localConfigurationFileContent .= 'return ' . chr(10);
            $configLoader = \Helhum\Typo3ConfigHandling\ConfigLoaderFactory::buildLoader(
                \TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()->isProduction() ? 'production' : 'development'
            );
            $localConfigurationFileContent .= ArrayUtility::arrayExport($configLoader->load());
            $localConfigurationFileContent .= ';' . chr(10);
        }
        file_put_contents(
            $localConfigurationFile,
            $localConfigurationFileContent
        );
    }
}
