imports:
    - { resource: 'InstallSteps.yaml', type: console }

databaseData:
    arguments:
        adminUserName:
            value: 'admin'
        adminPassword:
            value: 'password'
        siteName:
            default: 'Helhum''s awesome TYPO3 Composer Distribution'

defaultConfiguration:
    arguments:
        siteSetupType:
            value: site

setupProject:
    type: Helhum\TYPO3\ConfigHandling\Install\Action\SetupConfigurationAction
    description: 'Set up project settings'
    customOverrideSettings: '%env(TYPO3_INSTALL_OVERRIDE_SETTINGS_FILE)%'
    customSettings:
        arguments:
            defaultLanguageDomain:
                type: string
                value: '%env(TYPO3_INSTALL_SITE_URL)%'
                description: 'Website URL (including scheme, host, port)'
                configPath: 'Site.main.base'
                default: 'http://127.0.0.1:8080/'

fixSiteConfig:
    type: Helhum\TYPO3\ConfigHandling\Install\Action\FixupSiteConfigAction
    description: 'Finishing up project settings'
