name: awesome.typo3
type: php
docroot: public
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "8085"
router_https_port: "4434"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- awesome-typo3.test
mariadb_version: "10.2"
provider: default
hooks:
  post-start:
  - exec: res/scripts/setup.sh
upload_dir: private/fileadmin
working_dir:
  web: /var/www/html
omit_containers: [dba, ddev-ssh-agent]
use_dns_when_possible: true
timezone: Europe/Berlin
